// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okfvibkhyioalujlfuyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZnZpYmtoeWlvYWx1amxmdXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzE4MzYsImV4cCI6MjA2OTA0NzgzNn0.HUAxcyWbpXIo-YwZQ0CQE1ubNJ12a9mugYT7FthkMoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});